### ISSUE TITLE
bh != interface.good after forcing cash chain

### ISSUE THREAD

**Issue by molecular** [molecular/electrum#2]
After applying 6e9203fcfa4554817351a25d19a342bbf889e5e3 and freshly syncing headers from server, when sync is (just about) done, I get:

```
[profiler] on_update 0.0003
[electrum_unlimited.criptolayer.net] requesting chunk 236
[profiler] on_update 0.0777
[electrum_unlimited.criptolayer.net] requesting chunk 237
[profiler] on_update 0.0001
[Blockchain] block at height 478559 is not cash chain fork block. hash 00000000000000000019f112ec0a9982926f1258cdcc558dd7c3b7e5dc7fa148
[electrum_unlimited.criptolayer.net] blockchain request timed out
[Network] network: retrying connections
[shsmithgoggryfbx.onion] cannot resolve hostname
[14.3.70.9] connected
[14.3.70.9] binary search
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/nick/bitcoin/electron-cash/lib/network.py", line 966, in run
    self.wait_on_sockets()
  File "/home/nick/bitcoin/electron-cash/lib/network.py", line 933, in wait_on_sockets
    self.process_responses(interface)
  File "/home/nick/bitcoin/electron-cash/lib/network.py", line 625, in process_responses
    self.process_response(interface, response, callbacks)
  File "/home/nick/bitcoin/electron-cash/lib/network.py", line 571, in process_response
    self.on_get_header(interface, response)
  File "/home/nick/bitcoin/electron-cash/lib/network.py", line 854, in on_get_header
    assert bh == interface.good
AssertionError
 ```

**Comment by molecular** [comment]
obsolete, cash chain forcing wasn't merged
